name: PyWall CI
on:
  # push:
    # branches: [ master ]
  # pull_request:
    # branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
      - name: Install dependencies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: pipenv install && pipenv install pyinstaller
      - name: env
        run: pipenv --venv
      - name: Build
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: pipenv run pyinstaller pyinstaller main.py --noconfirm --onedir --window --uac-admin -n "PyWall" --icon "img/PyWall.ico" --add-data "img;img/" --add-data "src;src/" --add-data ""{steps.env.output}""\Lib\site-packages\context_menu;context_menu\"
      - name: Zip artifact
        uses: vimtor/action-zip@v1
        with:
          files: dist/PyWall
          dest: PyWall.zip
     
      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          path: dist/PyWall.zip
        
      
