name: PyWall CI
on:
  push:
    branches: [master]
  # pull_request:
  # branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies and build
        shell: pwsh
        run: |
              # Ensure dependencies are installed
              Write-Host "Installing dependencies..." -ForegroundColor Green
              pip install pipenv
              pipenv lock -d
              pipenv sync -d
              # Activate virtual environment
              Write-Host "Activating virtual environment..." -ForegroundColor Green
              $env:PIPENV_VENV_IN_PROJECT = "true"
              $venvPath = & pipenv --venv
              # Build the application
              Write-Host "Building PyWall..." -ForegroundColor Green
              cd ..
              pipenv run pyinstaller "main.py" --noconfirm --onedir --uac-admin -n "PyWall" --icon "img/PyWall.ico" --contents-directory . --add-data "img;img/" --add-data "src;src/" --add-data "$venvPath\Lib\site-packages\context_menu;context_menu/"
              Write-Host "Build completed successfully!" -ForegroundColor Green
              Write-Host "The executable can be found in the dist/PyWall directory." -ForegroundColor Cyan
   
      - name: Zip artifact
        uses: vimtor/action-zip@v1.2
        with:
          files: dist/PyWall
          dest: PyWall.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'PyWall'
          path: ${{ github.workspace }}/PyWall.zip
