name: PyWall CI
on:
  push:
    branches: [master]
  # pull_request:
  # branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: palewire/install-python-pipenv-pipfile@v4
        with: 
            python-version: 3.11
      - name: Build
        run: |
              echo Building PyWall...
              pipenv run pyinstaller "main.py" --noconfirm --onedir --uac-admin -n "PyWall" --icon "img/PyWall.ico" --contents-directory . --add-data "img;img/" --add-data "src;src/" --add-data "C:\Users\runneradmin\.virtualenvs\PyWall-65-QOBsy\Lib\site-packages\context_menu;context_menu/"
              echo Build success
   
      - name: Zip artifact
        uses: vimtor/action-zip@v1.2
        with:
          files: dist/PyWall
          dest: PyWall.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'PyWall'
          path: ${{ github.workspace }}/PyWall.zip
